2023 update
rcos/rcos-handbook pull request #172
Opened 2023-01-12 17:16 UTC by alicebibaud

I updated quite a lot based on what we've been talking about throughout last semester and the beginning of this one.  Please take a look here, let me know what you think, and hopefully, we can push this to master!

I intend to do a lot more updating to make sure everything is up to date, so this is by no means a finished set of additions.

2023-01-12 22:12 UTC, bnidevs requested changes

2023-01-12 22:12 UTC, bnidevs commented on docs/grading/status_updates.md
> +List direct links to your contributions. Mentors need to be able to see proof of your work by following these links. Links to your commits, issues, etc. are desirable.
add that contributions can include learning summaries, following tutorials on a sample repo, etc.

2023-01-12 22:21 UTC, anugrahaawasthi commented on docs/grading/finalpresentationguideline.md
> +We will have presentations on your projects during meeting times from 4/12-4/26. Every meeting has 2 rooms. You are expected to present with your room. You only need to come to DCC 318 on your presen
in the same spirit we should replace 318 with "our large group meeting room" or similar.

2023-01-13 15:35 UTC, wdturner commented on docs/events/workshops.md
> +Anyone in RCOS is allowed to host a workshop. As of Spring 2023, Mentors are required to host at least two.
I thought we were requiring students to attend 2. Is this doable? Do we have the time in a 16 week semester? The hope is that our mentoring cadre will grow to match our enrollment.

2023-01-13 20:24 UTC, closed without merging